version: '3.4'

services:
  python:
    image: 'iammaxim/devops:latest'
    ports:
      - "8000:8000"
# You may uncomment this to use docker-compose environment for development.
#    volumes:
#      - ./app_python/src:/app/src