version: '3.4'

services:
  python:
    image: 'iammaxim/devops:latest'
    ports:
      - "8000:8000"
    logging:
      driver: "local"
      options:
        max-size: "10m"
    mem_limit: 256m
    volumes:
    - "./timeserver_data:/volume"