Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # require plugin https://github.com/leighmcculloch/vagrant-docker-compose
  # Vagrant will automatically prompt for plugin install if it is missing.
  config.vagrant.plugins = "vagrant-docker-compose"

  # install docker and docker-compose
  config.vm.provision :docker
  config.vm.provision :docker_compose

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  # Forward port 8000, used for time server app
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Copy docker-compose.yml to the VM
  config.vm.provision "file", source: "../docker-compose.yml", destination: "docker-compose.yml"

  # Start docker-compose on up
  config.trigger.after :up do |trigger|
    trigger.info = "Starting docker-compose..."
    trigger.run_remote = {inline: 'docker-compose up -d'}
  end

  # Start docker-compose on provision
  config.vm.provision "shell",
    inline: 'docker-compose up -d'

end
