all:
  hosts:
    vagrant-vm:
      # TODO: use secrets for non-local production environment.
      # Since nobody (external) can exploit services exposed on loopback interface, we do not care about credential 
      # privacy here.
      ansible_user: root
      ansible_password: root
      ansible_host: 127.0.0.1
      ansible_port: 2222

  children: {}
