apiVersion: v1
kind: Service
metadata:
  name: {{ include "timeserver-chart.fullname" . }}
  labels:
    {{- include "timeserver-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "timeserver-chart.selectorLabels" . | nindent 4 }}
