- name: Create app directory directory.
  file:
    path: /opt/app_python/
    state: directory
    mode: 0755

- name: Install Time Server docker-compose file.
  ansible.builtin.template:
    src: ../templates/docker-compose.j2
    dest: /opt/app_python/docker-compose.yml

- name: Deploy docker-compose confugration.
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: /opt/app_python/